import time as T
import random as R

# import RPi.GPIO as GPIO
# import dht11

# GPIO.setwarnings(False)
# GPIO.setmode(GPIO.BCM)
# GPIO.cleanup()

# task 2 : pin setup
# instance = dht11.DHT11(pin=21)

# task 1 : generating random values for temperature and humidity
def random_dht11():
    # Temp range of DHT 11 sensor is 0 - 50
    rand_temp = R.randint(0,51)
    # Humidity values provided by DHT sensors are of the range 20% - 90%
    rand_humi = R.randint(20,91)
    # return values as if dht 11 sensor is producing these values
    return rand_temp,rand_humi

while True:
    # read temperature and humidity values generated by dht11 sensor
    # result = instance.read()
    # reading temperature and humidity values generated by our random generator
    temp, humi = random_dht11()
    # task 3 : controlling part; set threshold as 24 deg
    thresh = 24
    if temp >= thresh:
        print(f"The Weather is Hot and Humidity is {humi}%")
    else:
        print(f"The weather is Cold and Humidity is {humi}%")
    T.sleep(5)